name: Publish Test

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "my-tag-1"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
